
// Objective-C API for talking to the following Go packages
//
//	golang.getoutline.org/sdk/x/mobileproxy
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobileproxy_FRAMEWORK_H__
#define __Mobileproxy_FRAMEWORK_H__

#include "Mobileproxy.objc.h"
#include "Universe.objc.h"

#endif
