// Objective-C API for talking to golang.getoutline.org/sdk/x/mobileproxy Go package.
//   gobind -lang=objc golang.getoutline.org/sdk/x/mobileproxy
//
// File is generated by gobind. Do not edit.

#ifndef __Mobileproxy_H__
#define __Mobileproxy_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MobileproxyProxy;
@class MobileproxySmartDialerOptions;
@class MobileproxyStreamDialer;
@class MobileproxyStringList;
@protocol MobileproxyLogWriter;
@class MobileproxyLogWriter;
@protocol MobileproxyStrategyCache;
@class MobileproxyStrategyCache;

@protocol MobileproxyLogWriter <NSObject>
- (BOOL)writeString:(NSString* _Nullable)s n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

@protocol MobileproxyStrategyCache <NSObject>
/**
 * Get retrieves the string value associated with the given key.
It should return an empty (or `null`) string if the key is not found.
 */
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
/**
 * Put adds the string value with the given key to the cache.
If called with empty (or `null`) value, it should remove the cache entry.
 */
- (void)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

/**
 * Proxy enables you to get the actual address bound by the server and stop the service when no longer needed.
 */
@interface MobileproxyProxy : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * AddURLProxy sets up a URL-based proxy handler that activates when an incoming HTTP request matches
the specified path prefix. The pattern must represent a path segment, which is checked against
the path of the incoming request.

This function is particularly useful for libraries or components that accept URLs but do not support proxy
configuration directly. By leveraging AddURLProxy, such components can route requests through a proxy by
constructing URLs in the format "http://${HOST}:${PORT}/${PATH}/${URL}", where "${URL}" is the target resource.
For instance, using "http://localhost:8080/proxy/https://example.com" routes the request for "https://example.com"
through a proxy at "http://localhost:8080/proxy".

The path should start with a forward slash ('/') for clarity, but one will be added if missing.

The function associates the given 'dialer' with the specified 'path', allowing different dialers to be used for
different path-based proxies within the same application in the future. currently we only support one URL proxy.
 */
- (void)addURLProxy:(NSString* _Nullable)path dialer:(MobileproxyStreamDialer* _Nullable)dialer;
/**
 * Address returns the IP and port the server is bound to.
 */
- (NSString* _Nonnull)address;
/**
 * Host returns the IP the server is bound to.
 */
- (NSString* _Nonnull)host;
/**
 * Port returns the port the server is bound to.
 */
- (long)port;
/**
 * Stop gracefully stops the proxy service, waiting for at most timeout seconds before forcefully closing it.
The function takes a timeoutSeconds number instead of a [time.Duration] so it's compatible with Go Mobile.
 */
- (void)stop:(long)timeoutSeconds;
@end

/**
 * SmartDialerOptions specifies the options for creating a "Smart Dialer".
A "Smart Dialer" automatically selects the best DNS/TLS strategy to connect to the internet.
 */
@interface MobileproxySmartDialerOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSmartDialerOptions initializes the required options for creating a "Smart Dialer".

`testDomains` are used to test connectivity for each DNS/TLS strategy.
`config` defines the strategies to test. For an example, see:
https://golang.getoutline.org/sdk/blob/main/x/examples/smart-proxy/config.yaml
 */
- (nullable instancetype)init:(MobileproxyStringList* _Nullable)testDomains config:(NSString* _Nullable)config;
/**
 * NewStreamDialer creates a new "Smart" StreamDialer using the configured options.
It finds the best-performing DNS/TLS strategy and returns a StreamDialer that uses this strategy.
 */
- (MobileproxyStreamDialer* _Nullable)newStreamDialer:(NSError* _Nullable* _Nullable)error;
// skipped method SmartDialerOptions.RegisterFallbackParser with unsupported parameter or return types

/**
 * SetLogWriter configures an optional LogWriter for logging the strategy selection process.
 */
- (void)setLogWriter:(id<MobileproxyLogWriter> _Nullable)logw;
/**
 * SetStrategyCache configures an optional StrategyCache to store successful strategies,
speeding up NewDialer calls.
 */
- (void)setStrategyCache:(id<MobileproxyStrategyCache> _Nullable)cache;
@end

/**
 * StreamDialer encapsulates the logic to create stream connections (like TCP).
 */
@interface MobileproxyStreamDialer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewStreamDialerFromConfig creates a [StreamDialer] based on the given config.
The config format is specified in https://pkg.go.dev/golang.getoutline.org/sdk/x/configurl#hdr-Config_Format.
 */
- (nullable instancetype)initFromConfig:(NSString* _Nullable)transportConfig;
// skipped field StreamDialer.StreamDialer with unsupported type: golang.getoutline.org/sdk/transport.StreamDialer

// skipped method StreamDialer.DialStream with unsupported parameter or return types

@end

/**
 * StringList allows us to pass a list of strings to the Go Mobile functions, since Go Mobile doesn't
support slices as parameters.
 */
@interface MobileproxyStringList : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Append adds the string value to the end of the list.
 */
- (void)append:(NSString* _Nullable)value;
@end

/**
 * NewListFromLines creates a StringList by splitting the input string on new lines.
 */
FOUNDATION_EXPORT MobileproxyStringList* _Nullable MobileproxyNewListFromLines(NSString* _Nullable lines);

/**
 * NewSmartDialerOptions initializes the required options for creating a "Smart Dialer".

`testDomains` are used to test connectivity for each DNS/TLS strategy.
`config` defines the strategies to test. For an example, see:
https://golang.getoutline.org/sdk/blob/main/x/examples/smart-proxy/config.yaml
 */
FOUNDATION_EXPORT MobileproxySmartDialerOptions* _Nullable MobileproxyNewSmartDialerOptions(MobileproxyStringList* _Nullable testDomains, NSString* _Nullable config);

/**
 * NewSmartStreamDialer automatically selects a DNS and TLS strategy to use, and returns a [StreamDialer]
that will use the selected strategy.
It uses testDomains to find a strategy that works when accessing those domains.
The strategies to search are given in the searchConfig. An example can be found in
https://golang.getoutline.org/sdk/x/examples/smart-proxy/config.yaml

Deprecated: Use [SmartDialerOptions] NewStreamDialer instead.
 */
FOUNDATION_EXPORT MobileproxyStreamDialer* _Nullable MobileproxyNewSmartStreamDialer(MobileproxyStringList* _Nullable testDomains, NSString* _Nullable searchConfig, id<MobileproxyLogWriter> _Nullable logWriter, NSError* _Nullable* _Nullable error);

/**
 * NewStderrLogWriter creates a [LogWriter] that writes to the standard error output.
 */
FOUNDATION_EXPORT id<MobileproxyLogWriter> _Nullable MobileproxyNewStderrLogWriter(void);

/**
 * NewStreamDialerFromConfig creates a [StreamDialer] based on the given config.
The config format is specified in https://pkg.go.dev/golang.getoutline.org/sdk/x/configurl#hdr-Config_Format.
 */
FOUNDATION_EXPORT MobileproxyStreamDialer* _Nullable MobileproxyNewStreamDialerFromConfig(NSString* _Nullable transportConfig, NSError* _Nullable* _Nullable error);

/**
 * RunProxy runs a local web proxy that listens on localAddress, and handles proxy requests by
establishing connections to requested destination using the [StreamDialer].
 */
FOUNDATION_EXPORT MobileproxyProxy* _Nullable MobileproxyRunProxy(NSString* _Nullable localAddress, MobileproxyStreamDialer* _Nullable dialer, NSError* _Nullable* _Nullable error);

@class MobileproxyLogWriter;

@class MobileproxyStrategyCache;

/**
 * LogWriter is used as a sink for logging.
 */
@interface MobileproxyLogWriter : NSObject <goSeqRefInterface, MobileproxyLogWriter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)writeString:(NSString* _Nullable)s n:(long* _Nullable)n error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * StrategyCache enables storing and retrieving successful strategies.
Clients are required to provide a platform-specific implementation of this interface.
 */
@interface MobileproxyStrategyCache : NSObject <goSeqRefInterface, MobileproxyStrategyCache> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * Get retrieves the string value associated with the given key.
It should return an empty (or `null`) string if the key is not found.
 */
- (NSString* _Nonnull)get:(NSString* _Nullable)key;
/**
 * Put adds the string value with the given key to the cache.
If called with empty (or `null`) value, it should remove the cache entry.
 */
- (void)put:(NSString* _Nullable)key value:(NSString* _Nullable)value;
@end

#endif
